server:
  port: 8092
spring:
  application:
    name: spring-framework-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
logging:
  config: classpath:logback.xml
turbine:
  app-config: spring-framework-user,spring-framework-explore,spring-framework-system
hystrix:
  dashboard:
    enable-ignore-connection-close-header: true
  metrics:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
