server:
  port: 8093
  #address: 192.168.99.5
spring:
  application:
    name: spring-framework-config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
logging:
  config: classpath:logback.xml

