server:
  port: 8093
  #address: 192.168.99.5
spring:
  application:
    name: spring-framework-config
  cloud:
    config:
#      profile: dev
      server:
        #        git:
        #          uri: https://github.com/lovezmming/spring-cloud-config.git
        #          search-paths: dev
        #          username:
        #          password:
        native:
          search-locations: E:/study/spring-framework-core/database/dev
  profiles:
    active: native

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
logging:
  config: classpath:logback.xml

