server:
  port: 8081
  #address: 192.168.99.5

spring:
  application:
    name: spring-framework-manager
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/

logging:
  config: classpath:logback.xml
