server:
  port: 8088

spring:
  application:
    name: spring-framework-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    appname: eureka
logging:
  config: classpath:logback.xml
