server:
  port: 8090
  #address: 192.168.99.5

spring:
  application:
    name: spring-framework-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    appname: master
logging:
  config: classpath:logback.xml
