CREATE SCHEMA IF NOT EXISTS `COMMODITY` DEFAULT CHARACTER SET utf8;
USE `COMMODITY` ;

DROP TABLE IF EXISTS `commodity` ;
CREATE TABLE IF NOT EXISTS `commodity` (
  `ID` CHAR(21) NOT NULL,
  `NAME` VARCHAR(128) NOT NULL,
  `URL` VARCHAR(128) NULL,
  `PRICE` INT NULL,
  `DESCRIPTION` VARCHAR(1024) NOT NULL,
  `STATUS` TINYINT(1) NOT NULL,
  `UPDATE_USER` CHAR(21) NOT NULL,
  `CREATE_USER` CHAR(21) NOT NULL,
  `CREATE_TIME` DATETIME(3) NOT NULL,
  `UPDATE_TIME` DATETIME(3) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;