CREATE SCHEMA IF NOT EXISTS `SYSTEM` DEFAULT CHARACTER SET utf8 ;
USE `SYSTEM` ;

DROP TABLE IF EXISTS `about` ;
CREATE TABLE IF NOT EXISTS `about` (
  `ID` CHAR(21) NOT NULL,
  `NAME` VARCHAR(128) NOT NULL,
  `DESCRIPTION` VARCHAR(1024) NOT NULL,
  `STATUS` TINYINT(1) NOT NULL,
  `UPDATE_USER` CHAR(21) NOT NULL,
  `CREATE_USER` CHAR(21) NOT NULL,
  `CREATE_TIME` DATETIME(3) NOT NULL,
  `UPDATE_TIME` DATETIME(3) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;
