CREATE SCHEMA IF NOT EXISTS `USER` DEFAULT CHARACTER SET utf8;
USE `USER` ;

DROP TABLE IF EXISTS `sign_in` ;
CREATE TABLE IF NOT EXISTS `sign_in` (
  `ID` CHAR(21) NOT NULL,
  `USER_ID` CHAR(21) NOT NULL,
  `STATUS` TINYINT(1) NOT NULL,
  `UPDATE_USER` CHAR(21) NOT NULL,
  `CREATE_USER` CHAR(21) NOT NULL,
  `CREATE_TIME` DATETIME(3) NOT NULL,
  `UPDATE_TIME` DATETIME(3) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `user` ;
CREATE TABLE IF NOT EXISTS `user` (
  `ID` CHAR(21) NOT NULL,
  `EXPERIENCE` INT NOT NULL,
  `LEVEL` INT NOT NULL,
  `USER_NAME` VARCHAR(128) NOT NULL,
  `PASS_WORD` VARCHAR(128) NOT NULL,
  `PRIVATE_PASS_WORD` VARCHAR(128) NOT NULL,
  `NAME` VARCHAR(128) NOT NULL,
  `GENDER` INT NULL,
  `BIRTHDAY` DATETIME(3) NULL,
  `PHONE_NUMBER` VARCHAR(18) NOT NULL,
  `UPDATE_USER` CHAR(21) NOT NULL,
  `CREATE_USER` CHAR(21) NOT NULL,
  `CREATE_TIME` DATETIME(3) NOT NULL,
  `UPDATE_TIME` DATETIME(3) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `user_role_relation` ;
CREATE TABLE IF NOT EXISTS `user_role_relation` (
  `ID` CHAR(21) NOT NULL,
  `USER_ID` CHAR(21) NULL,
  `ROLE_ID` CHAR(21) NULL,
  `UPDATE_USER` CHAR(21) NOT NULL,
  `CREATE_USER` CHAR(21) NOT NULL,
  `CREATE_TIME` DATETIME(3) NOT NULL,
  `UPDATE_TIME` DATETIME(3) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `user_permission_relation` ;
CREATE TABLE IF NOT EXISTS `user_permission_relation` (
  `ID` CHAR(21) NOT NULL,
  `USER_ID` CHAR(21) NULL,
  `PERMISSION_ID` CHAR(21) NULL,
  `UPDATE_USER` CHAR(21) NOT NULL,
  `CREATE_USER` CHAR(21) NOT NULL,
  `CREATE_TIME` DATETIME(3) NOT NULL,
  `UPDATE_TIME` DATETIME(3) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `role` ;
CREATE TABLE IF NOT EXISTS `role` (
  `ID` CHAR(21) NOT NULL,
  `NAME` VARCHAR(1024) NULL,
  `TYPE` VARCHAR(16) NULL,
  `STATUS` TINYINT(1) NULL,
  `UPDATE_USER` CHAR(21) NOT NULL,
  `CREATE_USER` CHAR(21) NOT NULL,
  `CREATE_TIME` DATETIME(3) NOT NULL,
  `UPDATE_TIME` DATETIME(3) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `permission` ;
CREATE TABLE IF NOT EXISTS `permission` (
  `ID` CHAR(21) NOT NULL,
  `NAME` VARCHAR(1024) NULL,
  `TYPE` VARCHAR(16) NULL,
  `STATUS`TINYINT(1) NULL,
  `UPDATE_USER` CHAR(21) NOT NULL,
  `CREATE_USER` CHAR(21) NOT NULL,
  `CREATE_TIME` DATETIME(3) NOT NULL,
  `UPDATE_TIME` DATETIME(3) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `level` ;
CREATE TABLE IF NOT EXISTS `level` (
  `ID` CHAR(32) NOT NULL,
  `NAME` VARCHAR(1024) NULL,
  `LEVEL` INT NULL,
  `EXPERIENCE` INT NULL,
  `UPDATE_USER` CHAR(21) NOT NULL,
  `CREATE_USER` CHAR(21) NOT NULL,
  `CREATE_TIME` DATETIME(3) NOT NULL,
  `UPDATE_TIME` DATETIME(3) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;