package com.spring.framework.system.database.mapper;

import com.spring.framework.system.database.po.About;
import java.util.List;

public interface AboutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about
     *
     * @mbg.generated
     */
    int insert(About record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about
     *
     * @mbg.generated
     */
    About selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about
     *
     * @mbg.generated
     */
    List<About> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(About record);
}