database:
  names: user,explore
  user:
    url: jdbc:mysql://localhost:3306/zmstd?useUnicode=true&characterEncoding=utf-8&useSSL=true
    class: com.mysql.jdbc.Driver
    username: root
    password:
  explore:
    url: jdbc:mysql://localhost:3306/zmstd?useUnicode=true&characterEncoding=utf-8&useSSL=true
    class: com.mysql.jdbc.Driver
    username: root
    password:
spring:
  datasource:
    driverclass: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/zmstd?useUnicode=true&characterEncoding=utf-8&useSSL=true