server:
  port: 8091
spring:
  application:
    name: spring-framework-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 20000
  routes:
    spring-framework-user:
      path: /user/**
      serviceId: spring-framework-user
#      url: http://localhost:9001/
    spring-framework-explore:
      path: /explore/**
      serviceId: spring-framework-explore
#      url: http://localhost:9002/
    spring-framework-system:
      path: /system/**
      serviceId: spring-framework-system
logging:
  config: classpath:logback.xml
