server:
  port: 8091
  #address: 192.168.99.5

spring:
  application:
    name: spring-framework-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
zuul:
  routes:
    spring-framework-user: /user/**
    spring-framework-explore: /explore/**

logging:
  config: classpath:logback.xml
