server:
  port: 9002
  #  address: 192.168.99.5
spring:
  application:
    name: spring-framework-explore
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
logging:
  config: classpath:logback.xml
feign:
  httpclient:
    enabled: true
