DROP TABLE IF EXISTS `sign_in` ;
CREATE TABLE IF NOT EXISTS `sign_in` (
  `ID` CHAR(32) NOT NULL,
  `USER_ID` CHAR(32) NOT NULL,
  `STATUS` VARCHAR(32) NULL,
  `CREATE_TIME` DATETIME(3) NULL,
  `UPDATE_TIME` DATETIME(3) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `user` ;
CREATE TABLE IF NOT EXISTS `user` (
  `ID` CHAR(32) NOT NULL,
  `ROLE_ID` CHAR(32) NULL,
  `EXPERIENCE_ID` CHAR(32) NULL,
  `USER_NAME` VARCHAR(128) NOT NULL,
  `PASS_WORD` VARCHAR(128) NOT NULL,
  `PRIVATE_PASS_WORD` VARCHAR(128) NOT NULL,
  `NAME` VARCHAR(128) NOT NULL,
  `GENDER` INT NULL,
  `BIRTHDAY` DATETIME(3) NULL,
  `PHONE_NUMBER` VARCHAR(18) NOT NULL,
  `CREATE_TIME` DATETIME(3) NULL,
  `UPDATE_TIME` DATETIME(3) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `role` ;
CREATE TABLE IF NOT EXISTS `role` (
  `ID` CHAR(32) NOT NULL,
  `NAME` VARCHAR(1024) NULL,
  `TYPE` VARCHAR(32) NULL,
  `STATUS` VARCHAR(32) NULL,
  `CREATE_TIME` DATETIME(3) NULL,
  `UPDATE_TIME` DATETIME(3) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `experience` ;
CREATE TABLE IF NOT EXISTS `experience` (
  `ID` CHAR(32) NOT NULL,
  `NAME` VARCHAR(1024) NULL,
  `SCORE` INT NULL,
  `LEVEL` INT NULL,
  `EXPERIENCE` INT NULL,
  `CREATE_TIME` DATETIME(3) NULL,
  `UPDATE_TIME` DATETIME(3) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `level` ;
CREATE TABLE IF NOT EXISTS `level` (
  `ID` CHAR(32) NOT NULL,
  `NAME` VARCHAR(1024) NULL,
  `LEVEL` INT NULL,
  `EXPERIENCE` INT NULL,
  `CREATE_TIME` DATETIME(3) NULL,
  `UPDATE_TIME` DATETIME(3) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;